services:
  - type: web
    name: smartlocker-qr
    runtime: node
    plan: free
    region: ohio
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: PORT
        value: 3000
